services:
  - type: web
    name: lintao-deepseek-api
    env: node
    buildCommand: npm install
    startCommand: node server.prod.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
